### ISSUE TITLE
Extract fumen encoder/decoder to a separated package?

### ISSUE THREAD

**Issue by eight04** [knewjade/fumen-for-mobile-ts#2]
It seems that two files share similar code:
https://github.com/knewjade/fumen-preview-extension/blob/master/src/fumen/fumen.ts
https://github.com/knewjade/fumen-for-mobile-ts/blob/master/src/lib/fumen/fumen.ts

Is it possible to publish a package containing only the core algorithm to npm so users can use it without copy-paste? I'd like to create a tool that can convert fumen data into SVG images.

**Comment by knewjade** [comment]
Probably yes. I have never make npm package, so I was procrastinating it.  I will create a new repository for npm, so please give me a few days.

**Comment by eight04** [comment]
Found a site which also uses fumen:
https://github.com/davdav1233/tetris/blob/3244fb84561d77a7a05e25e1ca33d5701ef183f4/src/lib/fumen/fumen.ts

@davdav1233

**Comment by knewjade** [comment]
@eight04 I created new npm module: https://www.npmjs.com/package/tetris-fumen
This module includes a decoder/encoder and a simple field manipulation library now. If you have any problems or requests, please contact the following repository.
https://github.com/knewjade/tetris-fumen

thank you for your request.
